name: C/C++ CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code (including exercises)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Importante para trazer todas as branches
        ref: main       # Ou o nome da branch onde os exercícios estão

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build DataStructures
      run: |
        msbuild src/DataStructures/DataStructures.sln `
          /p:Configuration=Release `
          /p:Platform="x64"

    - name: Build LinkedList Exercises
      run: |
        msbuild "exercises/LinkedList/LinkedListExercises.sln" `
          /p:Configuration=Release `
          /p:Platform="x64"